// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8iQoHpq58OmpPtci6g9RrFiLpdOP3zEM',
    appId: '1:90971975408:web:6c8b664a5d22309e04dc35',
    messagingSenderId: '90971975408',
    projectId: 'test-a142c',
    authDomain: 'test-a142c.firebaseapp.com',
    storageBucket: 'test-a142c.appspot.com',
    measurementId: 'G-10RWXW605S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt24TPJ9vNSPHvkXyjrnUE36_h1_7NSSg',
    appId: '1:90971975408:android:0fc004b945e004cc04dc35',
    messagingSenderId: '90971975408',
    projectId: 'test-a142c',
    storageBucket: 'test-a142c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmtcTCoyk0Rir52GZSHIuHpGXqPHN8J4w',
    appId: '1:90971975408:ios:44d0615af13823eb04dc35',
    messagingSenderId: '90971975408',
    projectId: 'test-a142c',
    storageBucket: 'test-a142c.appspot.com',
    iosBundleId: 'com.example.chatMax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmtcTCoyk0Rir52GZSHIuHpGXqPHN8J4w',
    appId: '1:90971975408:ios:f54698ed72d3f75e04dc35',
    messagingSenderId: '90971975408',
    projectId: 'test-a142c',
    storageBucket: 'test-a142c.appspot.com',
    iosBundleId: 'com.example.chatMax.RunnerTests',
  );
}
